kind: ServiceAccount
apiVersion: v1
metadata:
  name: pvmigrate
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvmigrate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pvmigrate
subjects:
  - kind: ServiceAccount
    name: pvmigrate
    namespace: default
